from typing import Protocol

from app.models import User


class UserRepository(Protocol):
    def get_all(self) -> list[User]: ...
    def get_by_id(self, id: int) -> User | None: ...
    def delete(self, user: User) -> None: ...
    def save(self, user: User) -> User: ...
