from typing import List

from app.domain.entities.order import Order


class OrderRepository:
    def get_all(self) -> List[Order]: ...
    def save(self, order: Order) -> Order: ...
    def delete(self, id: int) -> None: ...
    def update(self, id: int, order: Order) -> Order: ...
